/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as DealDealIdRouteImport } from './routes/deal.$dealId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const DealDealIdRoute = DealDealIdRouteImport.update({
  id: '/deal/$dealId',
  path: '/deal/$dealId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pipeline': typeof PipelineRoute
  '/deal/$dealId': typeof DealDealIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pipeline': typeof PipelineRoute
  '/deal/$dealId': typeof DealDealIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pipeline': typeof PipelineRoute
  '/deal/$dealId': typeof DealDealIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pipeline' | '/deal/$dealId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pipeline' | '/deal/$dealId'
  id: '__root__' | '/' | '/pipeline' | '/deal/$dealId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PipelineRoute: typeof PipelineRoute
  DealDealIdRoute: typeof DealDealIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deal/$dealId': {
      id: '/deal/$dealId'
      path: '/deal/$dealId'
      fullPath: '/deal/$dealId'
      preLoaderRoute: typeof DealDealIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PipelineRoute: PipelineRoute,
  DealDealIdRoute: DealDealIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
